[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:Using extra keyword arguments on `Field` is deprecated.*:pydantic.warnings.PydanticDeprecatedSince20:ray\.serve\._private\.config
